movies = [
        {
            "id": "1",
            "title": "Zack Snyder's Justice League",
            "url": "https://www.imdb.com/title/tt12361974/?ref_=adv_li_tt",
            "rating": "8.3",
            "genre": "Action, Adventure, Fantasy",
            "year": "2021",
            "star": "Henry Cavill, Ben Affleck, Gal Gadot, Amy Adams",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BYjI3NDg0ZTEtMDEwYS00YWMyLThjYjktMTNlM2NmYjc1OGRiXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "242 min"
        },
        {
            "id": "2",
            "title": "Coming 2 America",
            "url": "https://www.imdb.com/title/tt6802400/?ref_=adv_li_tt",
            "rating": "5.4",
            "genre": "Comedy",
            "year": "2021",
            "star": "Eddie Murphy, Arsenio Hall, Shari Headley, Jermaine Fowler",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BZTMyY2Q2MDctMDFlMS00MWEzLTk1NmEtNDcxNzg1ZGJlNGU5XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "110 min"
        },
        {
            "id": "3",
            "title": "Cherry",
            "url": "https://www.imdb.com/title/tt9130508/?ref_=adv_li_tt",
            "rating": "6.6",
            "genre": "Crime, Drama",
            "year": "2021",
            "star": "Tom Holland, Ciara Bravo, Jack Reynor, Forrest Goodluck",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BOTZkMzlkYmItZDAyNy00NmZhLWE3MWItMzQyNDhkYzcwMTFmXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "142 min"
        },
        {
            "id": "4",
            "title": "Raya and the Last Dragon",
            "url": "https://www.imdb.com/title/tt5109280/?ref_=adv_li_tt",
            "rating": "7.5",
            "genre": "Animation, Action, Adventure",
            "year": "2021",
            "star": "Kelly Marie Tran, Awkwafina, Gemma Chan, Izaac Wang",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BZWNiOTc4NGItNGY4YS00ZGNkLThkOWEtMDE2ODcxODEwNjkwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "107 min"
        },
        {
            "id": "5",
            "title": "Yes Day",
            "url": "https://www.imdb.com/title/tt8521876/?ref_=adv_li_tt",
            "rating": "5.7",
            "genre": "Comedy, Family",
            "year": "2021",
            "star": "Jennifer Garner, Edgar Ramírez, Jenna Ortega, Julian Lerner",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BNTMwMzA4YzYtMzkwNC00N2ZhLTk5MjQtMjg3ODA3NDY3ZmVmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "86 min"
        },
        {
            "id": "6",
            "title": "Mortal Kombat",
            "url": "https://www.imdb.com/title/tt0293429/?ref_=adv_li_tt",
            "genre": "Action, Adventure, Fantasy",
            "year": "2021",
            "star": "Lewis Tan, Jessica McNamee, Josh Lawson, Hiroyuki Sanada",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BYzk1YTE2YzEtMWJkYi00NWJiLWFmOTgtNTUwODkzNDk4NWE1XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX67_CR0,0,67,98_AL_.jpg"
        },
        {
            "id": "7",
            "title": "Deadly Illusions",
            "url": "https://www.imdb.com/title/tt7897330/?ref_=adv_li_tt",
            "rating": "3.6",
            "genre": "Drama, Thriller",
            "year": "2021",
            "star": "Greer Grammer, Kristin Davis, Dermot Mulroney, Shanola Hampton",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BNzE3YTY3NjUtNWY0YS00NmVkLThhYmEtYWQxMjFhN2UwN2IxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UY98_CR1,0,67,98_AL_.jpg",
            "runtime": "114 min"
        },
        {
            "id": "8",
            "title": "Judas and the Black Messiah",
            "url": "https://www.imdb.com/title/tt9784798/?ref_=adv_li_tt",
            "rating": "7.6",
            "genre": "Biography, Drama, History",
            "year": "2021",
            "star": "Daniel Kaluuya, LaKeith Stanfield, Jesse Plemons, Dominique Fishback",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BOTYwNWNmM2UtNDhlOC00ZGQzLWI1MTMtMmZlMTFjM2Y1N2ZhXkEyXkFqcGdeQXVyMTY5Nzc4MDY@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "126 min"
        },
        {
            "id": "9",
            "title": "SAS: Red Notice",
            "url": "https://www.imdb.com/title/tt4479380/?ref_=adv_li_tt",
            "rating": "4.8",
            "genre": "Action",
            "year": "2021",
            "star": "Sam Heughan, Ruby Rose, Andy Serkis, Hannah John-Kamen",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BYzVjMWU4OGUtNGEyZS00MjJiLWIzNTMtNDk1NDdmMDUwYTAyXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "123 min"
        },
        {
            "id": "10",
            "title": "Godzilla vs. Kong",
            "url": "https://www.imdb.com/title/tt5034838/?ref_=adv_li_tt",
            "rating": "8.1",
            "genre": "Action, Sci-Fi, Thriller",
            "year": "2021",
            "star": "Alexander Skarsgård, Millie Bobby Brown, Rebecca Hall, Brian Tyree Henry",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BZmYzMzU4NjctNDI0Mi00MGExLWI3ZDQtYzQzYThmYzc2ZmNjXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "113 min"
        },
        {
            "id": "11",
            "title": "In the Heights",
            "url": "https://www.imdb.com/title/tt1321510/?ref_=adv_li_tt",
            "genre": "Drama, Music, Musical",
            "year": "2021",
            "star": "Stephanie Beatriz, Anthony Ramos, Lin-Manuel Miranda, Ariana Greenblatt",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BZDkzYmM5M2EtMjQxMS00ZDNiLTkwOWQtOTExZDdiMDIxNmQxXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "120 min"
        },
        {
            "id": "12",
            "title": "Chaos Walking",
            "url": "https://www.imdb.com/title/tt2076822/?ref_=adv_li_tt",
            "rating": "5.8",
            "genre": "Adventure, Sci-Fi",
            "year": "2021",
            "star": "Tom Holland, Daisy Ridley, Demián Bichir, David Oyelowo",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BYTcxYTk3MWQtZThlMS00ZjQ0LTg0NjktNGVkNWM2MTAyYWJmXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "109 min"
        },
        {
            "id": "13",
            "title": "Moxie",
            "url": "https://www.imdb.com/title/tt6432466/?ref_=adv_li_tt",
            "rating": "6.7",
            "genre": "Comedy, Drama, Music",
            "year": "2021",
            "star": "Hadley Robinson, Lauren Tsai, Alycia Pascual-Pena, Nico Hiraga",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BNjkwYzY2OTgtYjNiZi00YmNiLTk5YTQtZTQyZjM1YzA1ZmMwXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "111 min"
        },
        {
            "id": "14",
            "title": "Boss Level",
            "url": "https://www.imdb.com/title/tt7638348/?ref_=adv_li_tt",
            "rating": "6.9",
            "genre": "Action, Mystery, Sci-Fi",
            "year": "2021",
            "star": "Frank Grillo, Mel Gibson, Naomi Watts, Michelle Yeoh",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BNTVkODdiMjAtNmQ5Yy00OThhLTg4MDItYTZlYTFmN2E0M2M1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "94 min"
        },
        {
            "id": "15",
            "title": "The Vault",
            "url": "https://www.imdb.com/title/tt9742794/?ref_=adv_li_tt",
            "rating": "6.4",
            "genre": "Action, Adventure, Thriller",
            "year": "2021",
            "star": "Famke Janssen, Freddie Highmore, Astrid Bergès-Frisbey, Liam Cunningham",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BZTliM2M5MjktZmY2NC00NjdlLWE5YzUtNDU2NzA0MzkyMDNlXkEyXkFqcGdeQXVyMTE1Nzg4NjY0._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "118 min"
        },
        {
            "id": "16",
            "title": "The Unholy",
            "url": "https://www.imdb.com/title/tt9419056/?ref_=adv_li_tt",
            "genre": "Horror",
            "year": "2021",
            "star": "Jeffrey Dean Morgan, Cary Elwes, Katie Aselton, William Sadler",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BY2VhOTgxZGEtNGRiZi00NzVkLWE3MGEtZTRjNWEwY2MwZTI0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UY98_CR5,0,67,98_AL_.jpg"
        },
        {
            "id": "17",
            "title": "The Mauritanian",
            "url": "https://www.imdb.com/title/tt4761112/?ref_=adv_li_tt",
            "rating": "7.4",
            "genre": "Drama, Thriller",
            "year": "2021",
            "star": "Tahar Rahim, Nouhe Hamady Bari, Saadna Hamoud, Mohamed Yeslem Mousse",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BODJlMzdlYzItMzRkNi00NTE0LTliZjQtMTllNzkxNDVhNjkxXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "129 min"
        },
        {
            "id": "18",
            "title": "Black Widow",
            "url": "https://www.imdb.com/title/tt3480822/?ref_=adv_li_tt",
            "genre": "Action, Adventure, Sci-Fi",
            "year": "2021",
            "star": "Scarlett Johansson, Florence Pugh, David Harbour, Rachel Weisz",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BMzFiODE0ZDUtN2IxNC00OTI5LTg4OWItZTE2MjU4ZTk2NjM5XkEyXkFqcGdeQXVyNDYzODU1ODM@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "133 min"
        },
        {
            "id": "19",
            "title": "Tom and Jerry",
            "url": "https://www.imdb.com/title/tt1361336/?ref_=adv_li_tt",
            "rating": "5.2",
            "genre": "Animation, Comedy, Family",
            "year": "2021",
            "star": "Chloë Grace Moretz, Michael Peña, Colin Jost, Tom",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BYzE3ODhiNzAtOWY4MS00NTdiLThmNDctNDM4NjRiNGFmYjI1XkEyXkFqcGdeQXVyMTI2ODM1ODUw._V1_UY98_CR5,0,67,98_AL_.jpg",
            "runtime": "101 min"
        },
        {
            "id": "20",
            "title": "The Little Things",
            "url": "https://www.imdb.com/title/tt10016180/?ref_=adv_li_tt",
            "rating": "6.3",
            "genre": "Crime, Drama, Thriller",
            "year": "2021",
            "star": "Denzel Washington, Rami Malek, Jared Leto, Chris Bauer",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BOGFlNTdmYWQtM2IzMi00YTY3LTlmMDQtZDI5NGQ5MjYzZmEwXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "128 min"
        },
        {
            "id": "21",
            "title": "Paper Lives",
            "url": "https://www.imdb.com/title/tt13045890/?ref_=adv_li_tt",
            "rating": "6.5",
            "genre": "Drama",
            "year": "2021",
            "star": "Çagatay Ulusoy, Emir Ali Dogrul, Ersin Arici, Turgay Tanülkü",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BMWYxOTFlMjgtZTMyMS00OGRkLTk5ZGEtMDI2N2ZjN2EzZjg4XkEyXkFqcGdeQXVyMTIyMjI4OTkx._V1_UY98_CR1,0,67,98_AL_.jpg",
            "runtime": "96 min"
        },
        {
            "id": "22",
            "title": "Nobody (I)",
            "url": "https://www.imdb.com/title/tt7888964/?ref_=adv_li_tt",
            "rating": "7.8",
            "genre": "Action, Crime, Drama",
            "year": "2021",
            "star": "Bob Odenkirk, Aleksey Serebryakov, Connie Nielsen, Christopher Lloyd",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BMjM5YTRlZmUtZGVmYi00ZjE2LWIyNzAtOWVhMDk1MDdkYzhjXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "92 min"
        },
        {
            "id": "23",
            "title": "The Suicide Squad",
            "url": "https://www.imdb.com/title/tt6334354/?ref_=adv_li_tt",
            "genre": "Action, Adventure, Fantasy",
            "year": "2021",
            "star": "Margot Robbie, Idris Elba, John Cena, Joel Kinnaman",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BMzEzNzEyM2EtODM3OC00NWM4LTk3OTEtZjg3YjEzYTM1Zjk2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
        },
        {
            "id": "24",
            "title": "The Dig",
            "url": "https://www.imdb.com/title/tt3661210/?ref_=adv_li_tt",
            "rating": "7.1",
            "genre": "Biography, Drama, History",
            "year": "2021",
            "star": "Carey Mulligan, Ralph Fiennes, Lily James, Johnny Flynn",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BY2RmZmI0NDMtMGQzOC00YWU3LTkwYWUtMDRkNDBjZDg3YTkyXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "112 min"
        },
        {
            "id": "25",
            "title": "Cosmic Sin",
            "url": "https://www.imdb.com/title/tt11762434/?ref_=adv_li_tt",
            "rating": "2.5",
            "genre": "Action, Adventure, Sci-Fi",
            "year": "2021",
            "star": "Frank Grillo, Bruce Willis, Brandon Thomas Lee, Corey Large",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BMjI3YjY0YmItYWI5OS00MTgwLWI4NjYtM2M3N2RhNTljMGVkXkEyXkFqcGdeQXVyODEwNTMxOTA@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "88 min"
        },
        {
            "id": "26",
            "title": "Cruella",
            "url": "https://www.imdb.com/title/tt3228774/?ref_=adv_li_tt",
            "genre": "Comedy, Crime",
            "year": "2021",
            "star": "Emma Stone, Mark Strong, Emma Thompson, Paul Walter Hauser",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BZWQ1YjNiMTItZjkwZS00NDMyLThiOWEtNzBkMzAzMWU2ZDUwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
        },
        {
            "id": "27",
            "title": "Crisis",
            "url": "https://www.imdb.com/title/tt9731682/?ref_=adv_li_tt",
            "rating": "6.1",
            "genre": "Drama, Thriller",
            "year": "2021",
            "star": "Gary Oldman, Armie Hammer, Evangeline Lilly, Greg Kinnear",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BMjg5MDFiOGMtNDE1OS00NjQ5LThjZGEtZjExMjAwOTZiYTQ1XkEyXkFqcGdeQXVyNzk4OTQyODU@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "118 min"
        },
        {
            "id": "28",
            "title": "Army of the Dead",
            "url": "https://www.imdb.com/title/tt0993840/?ref_=adv_li_tt",
            "genre": "Action, Crime, Horror",
            "year": "2021",
            "star": "Dave Bautista, Ella Purnell, Ana de la Reguera, Samantha Win",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BMjNmN2QzNmEtMTBjNS00NTU5LTk3NjgtZTJkZjk5MzgzYzkyXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX67_CR0,0,67,98_AL_.jpg"
        },
        {
            "id": "29",
            "title": "Spider-Man: No Way Home",
            "url": "https://www.imdb.com/title/tt10872600/?ref_=adv_li_tt",
            "genre": "Action, Adventure, Sci-Fi",
            "year": "2021",
            "star": "Tom Holland, Benedict Cumberbatch, Zendaya, Marisa Tomei",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BNTMxOGI4OGMtMTgwMy00NmFjLWIyOTUtYjQ0OGQ4Mjk0YjNjXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
        },
        {
            "id": "30",
            "title": "Voyagers",
            "url": "https://www.imdb.com/title/tt9664108/?ref_=adv_li_tt",
            "genre": "Adventure, Sci-Fi, Thriller",
            "year": "2021",
            "star": "Colin Farrell, Tye Sheridan, Lily-Rose Depp, Isaac Hempstead Wright",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BZDIzODQyODQtYzIyYy00MDE5LWJmZjMtMDRmYTRkNzAyZjAzXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "108 min"
        },
        {
            "id": "31",
            "title": "The United States vs. Billie Holiday",
            "url": "https://www.imdb.com/title/tt8521718/?ref_=adv_li_tt",
            "rating": "6.3",
            "genre": "Biography, Drama, Music",
            "year": "2021",
            "star": "Andra Day, Trevante Rhodes, Garrett Hedlund, Natasha Lyonne",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BN2FjZDU0MGMtZDkxMi00M2VmLTkyNDQtNTFjYjIzYzMxMjgwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "130 min"
        },
        {
            "id": "32",
            "title": "Wrong Turn",
            "url": "https://www.imdb.com/title/tt9110170/?ref_=adv_li_tt",
            "rating": "5.4",
            "genre": "Horror, Thriller",
            "year": "2021",
            "star": "Charlotte Vega, Adain Bradley, Bill Sage, Emma Dumont",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BM2Y5ZWE2MTMtODE3ZC00NWQ4LWJkNzctNGY4Njg5NDY5MzNlXkEyXkFqcGdeQXVyNjUxMjc1OTM@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "109 min"
        },
        {
            "id": "33",
            "title": "Dune",
            "url": "https://www.imdb.com/title/tt1160419/?ref_=adv_li_tt",
            "genre": "Adventure, Drama, Sci-Fi",
            "year": "2021",
            "star": "Jason Momoa, Zendaya, Rebecca Ferguson, Timothée Chalamet",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BMGFkZGY0NTgtMGEyZC00YzhjLTkyOWItYzMzOTljMDA3ZjU2XkEyXkFqcGdeQXVyNzc4NTU3Njg@._V1_UX67_CR0,0,67,98_AL_.jpg"
        },
        {
            "id": "34",
            "title": "Girl in the Basement",
            "url": "https://www.imdb.com/title/tt13269536/?ref_=adv_li_tt",
            "rating": "6.3",
            "genre": "Crime, Thriller",
            "year": "2021",
            "star": "Jake Etheridge, Sydney Kowalske, Liam Pileggi, Emma Myers",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BMTdkYWE4ZGQtOGZkMy00ZTg1LWE5ODEtZWRlMjQ3NWQ2N2I2XkEyXkFqcGdeQXVyNjU0NTI0Nw@@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "88 min"
        },
        {
            "id": "35",
            "title": "Happily",
            "url": "https://www.imdb.com/title/tt9849004/?ref_=adv_li_tt",
            "rating": "5.2",
            "genre": "Comedy, Crime, Romance",
            "year": "2021",
            "star": "Kerry Bishé, Joel McHale, Al Madrigal, Natalie Zea",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BMGMxMzBhNDQtODJhNy00NDBmLWI5NTYtMTJkMjUxYjE0OWZjXkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "96 min"
        },
        {
            "id": "36",
            "title": "The White Tiger",
            "url": "https://www.imdb.com/title/tt6571548/?ref_=adv_li_tt",
            "rating": "7.2",
            "genre": "Crime, Drama",
            "year": "2021",
            "star": "Adarsh Gourav, Rajkummar Rao, Priyanka Chopra, Vedant Sinha",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BMDVkMDRkMzItN2EyYS00ZTI5LTljYzgtNzRmZDQ0OTQ3M2VjXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "125 min"
        },
        {
            "id": "37",
            "title": "The Matrix 4",
            "url": "https://www.imdb.com/title/tt10838180/?ref_=adv_li_tt",
            "genre": "Action, Sci-Fi",
            "year": "2021",
            "star": "Keanu Reeves, Priyanka Chopra, Carrie-Anne Moss, Jessica Henwick",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BN2I5NzlmMWYtYjIwYy00Y2ZiLWI0ODgtYjAxNDZiZGJlMjlhXkEyXkFqcGdeQXVyMzk1MDQ2MQ@@._V1_UY98_CR40,0,67,98_AL_.jpg"
        },
        {
            "id": "38",
            "title": "No Time to Die",
            "url": "https://www.imdb.com/title/tt2382320/?ref_=adv_li_tt",
            "genre": "Action, Adventure, Thriller",
            "year": "2021",
            "star": "Daniel Craig, Ana de Armas, Rami Malek, Ralph Fiennes",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BMTk3ZGM2YzQtMmYxYy00NDZjLWFmOTUtZTQwMzg0ZjA5ZjU3XkEyXkFqcGdeQXVyODk2NDQ3MTA@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "163 min"
        },
        {
            "id": "39",
            "title": "Free Guy",
            "url": "https://www.imdb.com/title/tt6264654/?ref_=adv_li_tt",
            "rating": "7.5",
            "genre": "Action, Adventure, Comedy",
            "year": "2021",
            "star": "Ryan Reynolds, Jodie Comer, Taika Waititi, Joe Keery",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BYTNjNzFiZTItNDM5NS00ODBhLTk5NmMtYzUyZWRmOWJjOTI3XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX67_CR0,0,67,98_AL_.jpg"
        },
        {
            "id": "40",
            "title": "Eternals",
            "url": "https://www.imdb.com/title/tt9032400/?ref_=adv_li_tt",
            "genre": "Action, Adventure, Drama",
            "year": "2021",
            "star": "Gemma Chan, Angelina Jolie, Salma Hayek, Richard Madden",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BOTYzMTlhM2ItMmFkYi00ZTJhLTg3MWQtNzM1NTRkM2NiNzRjXkEyXkFqcGdeQXVyNTE1NjY5Mg@@._V1_UY98_CR2,0,67,98_AL_.jpg"
        },
        {
            "id": "41",
            "title": "Sentinelle",
            "url": "https://www.imdb.com/title/tt11734264/?ref_=adv_li_tt",
            "rating": "4.7",
            "genre": "Action, Drama, Thriller",
            "year": "2021",
            "star": "Olga Kurylenko, Marilyn Lima, Michel Nabokoff, Martin Swabey",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BZDA5ZGVkZGMtNzk1My00YTU5LTgxYWUtODBlYmQyZjRjZjg4XkEyXkFqcGdeQXVyMTE5MTkxMDI2._V1_UY98_CR3,0,67,98_AL_.jpg",
            "runtime": "80 min"
        },
        {
            "id": "42",
            "title": "Willy's Wonderland",
            "url": "https://www.imdb.com/title/tt8114980/?ref_=adv_li_tt",
            "rating": "5.6",
            "genre": "Action, Comedy, Horror",
            "year": "2021",
            "star": "Nicolas Cage, Emily Tosta, Beth Grant, Ric Reitz",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BOTc3ZjVkYTYtMDZiMC00OTliLWE3OTEtYjY5NTBmNGJjYTBmXkEyXkFqcGdeQXVyNDExMzMxNjE@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "88 min"
        },
        {
            "id": "43",
            "title": "Palmer",
            "url": "https://www.imdb.com/title/tt6857376/?ref_=adv_li_tt",
            "rating": "7.3",
            "genre": "Drama",
            "year": "2021",
            "star": "Justin Timberlake, Juno Temple, Alisha Wainwright, Ryder Allen",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BYTZhNzM4MDktYWUwMC00NTE1LTlkN2UtM2Y5ODIwYjZmNTA2XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "110 min"
        },
        {
            "id": "44",
            "title": "Top Gun: Maverick",
            "url": "https://www.imdb.com/title/tt1745960/?ref_=adv_li_tt",
            "genre": "Action, Drama",
            "year": "2021",
            "star": "Tom Cruise, Jennifer Connelly, Miles Teller, Danny Ramirez",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BNTEyYTA5YWYtYmIxYS00NWRlLWExNjMtNjliZmVlZDgxNTBlXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX67_CR0,0,67,98_AL_.jpg"
        },
        {
            "id": "45",
            "title": "Mission: Impossible 7",
            "url": "https://www.imdb.com/title/tt9603212/?ref_=adv_li_tt",
            "genre": "Action, Adventure, Thriller",
            "year": "2021",
            "star": "Vanessa Kirby, Tom Cruise, Rebecca Ferguson, Hayley Atwell",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BNzlmY2QwMDgtMWFjNC00NGU0LWI2NDctNmMxYjkyNTk3MzZjXkEyXkFqcGdeQXVyMTA1OTYzOTUx._V1_UY98_CR5,0,67,98_AL_.jpg"
        },
        {
            "id": "46",
            "title": "Venom: Let There Be Carnage",
            "url": "https://www.imdb.com/title/tt7097896/?ref_=adv_li_tt",
            "genre": "Action, Horror, Sci-Fi",
            "year": "2021",
            "star": "Tom Hardy, Michelle Williams, Woody Harrelson, Stephen Graham",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BZjVmYzVjZWUtODE3NS00ZTExLThhMTUtNzU3ZGE2NGYwOWE4XkEyXkFqcGdeQXVyMTAwODc1OTcy._V1_UY98_CR15,0,67,98_AL_.jpg"
        },
        {
            "id": "47",
            "title": "Jathi Ratnalu",
            "url": "https://www.imdb.com/title/tt11306376/?ref_=adv_li_tt",
            "rating": "8.3",
            "genre": "Comedy",
            "year": "2021",
            "star": "Naveen Polishetty, Priyadarshi, Rahul Ramakrishna, Faria Abdullah",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BNTY5ZTcwOTEtNGU0MS00NWFkLWExZDUtMTljY2Y2YWMxNGNlXkEyXkFqcGdeQXVyMTI1NDAzMzM0._V1_UY98_CR1,0,67,98_AL_.jpg",
            "runtime": "145 min"
        },
        {
            "id": "48",
            "title": "Trust (II)",
            "url": "https://www.imdb.com/title/tt3986420/?ref_=adv_li_tt",
            "rating": "5.6",
            "genre": "Drama, Romance",
            "year": "2021",
            "star": "Victoria Justice, Matthew Daddario, Katherine McNamara, Lucien Laviscount",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BYjJlZDI4NTYtYjQzMi00ZmM0LWIxZDEtMzgwNTBjYjc4MTZlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "94 min"
        },
        {
            "id": "49",
            "title": "F9",
            "url": "https://www.imdb.com/title/tt5433138/?ref_=adv_li_tt",
            "genre": "Action, Adventure, Crime",
            "year": "2021",
            "star": "Vin Diesel, Michelle Rodriguez, Charlize Theron, Michael Rooker",
            "imgurl": "https://m.media-amazon.com/images/M/MV5BZDZlMjc0MTItZWY2YS00ZDJhLWI2M2MtODVjNWFmYTQxYmJjXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_UX67_CR0,0,67,98_AL_.jpg",
            "runtime": "145 min"
        },
        {
            "id": "50",
            "title": "House of Gucci",
            "url": "https://www.imdb.com/title/tt11214590/?ref_=adv_li_tt",
            "genre": "Crime, Drama, Thriller",
            "year": "2021",
            "star": "Jared Leto, Al Pacino, Adam Driver, Jeremy Irons",
            "imgurl": "https://m.media-amazon.com/images/S/sash/NapCxx-VwSOJtCZ.png"
        }
    ]
