movies = [
        {
            "id": "1",
            "title": "Zack Snyder's Justice League",
            "url": "https://www.imdb.com/title/tt12361974/?ref_=adv_li_tt",
            "desc": "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
            "youtubeurl": "https://www.youtube.com/embed/vM-Bja2Gy04",
            "rating": "8.3",
            "genre": "Action, Adventure, Fantasy",
            "year": "2021",
            "star": "Henry Cavill, Ben Affleck, Gal Gadot, Amy Adams",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/1.png?raw=true",
            "runtime": "242 min"
        },
        {
            "id": "2",
            "title": "Coming 2 America",
            "url": "https://www.imdb.com/title/tt6802400/?ref_=adv_li_tt",
            "desc": "The African monarch Akeem learns he has a long-lost son in the United States and must return to America to meet this unexpected heir and build a relationship with his son.",
            "youtubeurl": "https://www.youtube.com/embed/sY8gUtyeAKE",
            "rating": "5.4",
            "genre": "Comedy",
            "year": "2021",
            "star": "Eddie Murphy, Arsenio Hall, Shari Headley, Jermaine Fowler",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/2.png?raw=true",
            "runtime": "110 min"
        },
        {
            "id": "3",
            "title": "Cherry",
            "url": "https://www.imdb.com/title/tt9130508/?ref_=adv_li_tt",
            "desc": "Cherry drifts from college dropout to army medic in Iraq - anchored only by his true love, Emily. But after returning from the war with PTSD, his life spirals into drugs and crime as he struggles to find his place in the world.",
            "youtubeurl": "https://www.youtube.com/embed/Nt_wyydppg8",
            "rating": "6.6",
            "genre": "Crime, Drama",
            "year": "2021",
            "star": "Tom Holland, Ciara Bravo, Jack Reynor, Forrest Goodluck",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/3.png?raw=true",
            "runtime": "142 min"
        },
        {
            "id": "4",
            "title": "Raya and the Last Dragon",
            "url": "https://www.imdb.com/title/tt5109280/?ref_=adv_li_tt",
            "desc": "In a realm known as Kumandra, a re-imagined Earth inhabited by an ancient civilization, a warrior named Raya is determined to find the last dragon.",
            "youtubeurl": "https://www.youtube.com/embed/1VIZ89FEjYI",
            "rating": "7.5",
            "genre": "Animation, Action, Adventure",
            "year": "2021",
            "star": "Kelly Marie Tran, Awkwafina, Gemma Chan, Izaac Wang",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/4.png?raw=true",
            "runtime": "107 min"
        },
        {
            "id": "5",
            "title": "Yes Day",
            "url": "https://www.imdb.com/title/tt8521876/?ref_=adv_li_tt",
            "desc": "A mom and dad who usually say no decide to say yes to their kids' wildest requests with a few ground rules on a whirlwind day of fun and adventure.",
            "youtubeurl": "https://www.youtube.com/embed/Y-3Vr8Ut8d0",
            "rating": "5.7",
            "genre": "Comedy, Family",
            "year": "2021",
            "star": "Jennifer Garner, Edgar Ramírez, Jenna Ortega, Julian Lerner",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/5.png?raw=true",
            "runtime": "86 min"
        },
        {
            "id": "6",
            "title": "Mortal Kombat",
            "url": "https://www.imdb.com/title/tt0293429/?ref_=adv_li_tt",
            "desc": "MMA fighter Cole Young seeks out Earth's greatest champions in order to stand against the enemies of Outworld in a high stakes battle for the universe.",
            "youtubeurl": "https://www.youtube.com/embed/NYH2sLid0Zc",
            "genre": "Action, Adventure, Fantasy",
            "year": "2021",
            "star": "Lewis Tan, Jessica McNamee, Josh Lawson, Hiroyuki Sanada",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/6.png?raw=true"
        },
        {
            "id": "7",
            "title": "Deadly Illusions",
            "url": "https://www.imdb.com/title/tt7897330/?ref_=adv_li_tt",
            "desc": "After a bestselling novelist suffering from writer's block hires a new nanny for her children, the line between fiction and reality starts to blur.",
            "youtubeurl": "https://www.youtube.com/embed/cp34AFMKN9U",
            "rating": "3.6",
            "genre": "Drama, Thriller",
            "year": "2021",
            "star": "Greer Grammer, Kristin Davis, Dermot Mulroney, Shanola Hampton",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/7.png?raw=true",
            "runtime": "114 min"
        },
        {
            "id": "8",
            "title": "Judas and the Black Messiah",
            "url": "https://www.imdb.com/title/tt9784798/?ref_=adv_li_tt",
            "desc": "Offered a plea deal by the FBI, William O'Neal infiltrates the Illinois chapter of the Black Panther Party to gather intelligence on Chairman Fred Hampton.",
            "youtubeurl": "https://www.youtube.com/embed/sSjtGqRXQ9Y",
            "rating": "7.6",
            "genre": "Biography, Drama, History",
            "year": "2021",
            "star": "Daniel Kaluuya, LaKeith Stanfield, Jesse Plemons, Dominique Fishback",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/8.png?raw=true",
            "runtime": "126 min"
        },
        {
            "id": "9",
            "title": "SAS: Red Notice",
            "url": "https://www.imdb.com/title/tt4479380/?ref_=adv_li_tt",
            "desc": "A small army of well trained criminals led by Grace Lewis have hijacked a train deep beneath the English Channel.",
            "youtubeurl": "https://www.youtube.com/embed/hRuUB6RKExQ",
            "rating": "4.8",
            "genre": "Action",
            "year": "2021",
            "star": "Sam Heughan, Ruby Rose, Andy Serkis, Hannah John-Kamen",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/9.png?raw=true",
            "runtime": "123 min"
        },
        {
            "id": "10",
            "title": "Godzilla vs. Kong",
            "url": "https://www.imdb.com/title/tt5034838/?ref_=adv_li_tt",
            "desc": "The epic next chapter in the cinematic Monsterverse pits two of the greatest icons in motion picture history against one another - the fearsome Godzilla and the mighty Kong - with humanity caught in the balance.",
            "youtubeurl": "https://www.youtube.com/embed/odM92ap8_c0",
            "rating": "8.1",
            "genre": "Action, Sci-Fi, Thriller",
            "year": "2021",
            "star": "Alexander Skarsgård, Millie Bobby Brown, Rebecca Hall, Brian Tyree Henry",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/10.png?raw=true",
            "runtime": "113 min"
        },
        {
            "id": "11",
            "title": "In the Heights",
            "url": "https://www.imdb.com/title/tt1321510/?ref_=adv_li_tt",
            "desc": "The scent of a cafecito caliente hangs in the air just outside of the 181st Street subway stop. The likeable, magnetic bodega owner Usnavi saves every penny from his daily grind as he hopes, imagines and sings about a better life.",
            "youtubeurl": "https://www.youtube.com/embed/U0CL-ZSuCrQ",
            "genre": "Drama, Music, Musical",
            "year": "2021",
            "star": "Stephanie Beatriz, Anthony Ramos, Lin-Manuel Miranda, Ariana Greenblatt",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/11.png?raw=true",
            "runtime": "120 min"
        },
        {
            "id": "12",
            "title": "Chaos Walking",
            "url": "https://www.imdb.com/title/tt2076822/?ref_=adv_li_tt",
            "desc": "Two unlikely companions embark on a perilous adventure through the badlands of an unexplored planet as they try to escape a dangerous and disorienting reality, where all inner thoughts are seen and heard by everyone.",
            "youtubeurl": "https://www.youtube.com/embed/nRf4ZgzHoVw",
            "rating": "5.8",
            "genre": "Adventure, Sci-Fi",
            "year": "2021",
            "star": "Tom Holland, Daisy Ridley, Demián Bichir, David Oyelowo",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/12.png?raw=true",
            "runtime": "109 min"
        },
        {
            "id": "13",
            "title": "Moxie",
            "url": "https://www.imdb.com/title/tt6432466/?ref_=adv_li_tt",
            "desc": "Inspired by her mom's rebellious past and a confident new friend, a shy 16-year-old publishes an anonymous zine calling out sexism at her school.",
            "youtubeurl": "https://www.youtube.com/embed/Sf34qI1hjKU",
            "rating": "6.7",
            "genre": "Comedy, Drama, Music",
            "year": "2021",
            "star": "Hadley Robinson, Lauren Tsai, Alycia Pascual-Pena, Nico Hiraga",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/13.png?raw=true",
            "runtime": "111 min"
        },
        {
            "id": "14",
            "title": "Boss Level",
            "url": "https://www.imdb.com/title/tt7638348/?ref_=adv_li_tt",
            "desc": "A retired Special Forces officer is trapped in a never-ending time loop on the day of his death.",
            "youtubeurl": "https://www.youtube.com/embed/PGHD0bqjZWQ",
            "rating": "6.9",
            "genre": "Action, Mystery, Sci-Fi",
            "year": "2021",
            "star": "Frank Grillo, Mel Gibson, Naomi Watts, Michelle Yeoh",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/14.png?raw=true",
            "runtime": "94 min"
        },
        {
            "id": "15",
            "title": "The Vault",
            "url": "https://www.imdb.com/title/tt9742794/?ref_=adv_li_tt",
            "desc": "Follows a genius engineering graduate who is interested in the Bank of Spain's safe.",
            "youtubeurl": "https://www.youtube.com/embed/L41IJiageyg",
            "rating": "6.4",
            "genre": "Action, Adventure, Thriller",
            "year": "2021",
            "star": "Famke Janssen, Freddie Highmore, Astrid Bergès-Frisbey, Liam Cunningham",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/15.png?raw=true",
            "runtime": "118 min"
        },
        {
            "id": "16",
            "title": "The Unholy",
            "url": "https://www.imdb.com/title/tt9419056/?ref_=adv_li_tt",
            "desc": "A hearing-impaired girl is visited by the Virgin Mary and can suddenly hear, speak, and heal the sick. As people flock to witness her miracles, terrifying events unfold. Are they the work of the Virgin Mary or something much more sinister?",
            "youtubeurl": "https://www.youtube.com/embed/NmQiJPLYzPI",
            "genre": "Horror",
            "year": "2021",
            "star": "Jeffrey Dean Morgan, Cary Elwes, Katie Aselton, William Sadler",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/16.png?raw=true"
        },
        {
            "id": "17",
            "title": "The Mauritanian",
            "url": "https://www.imdb.com/title/tt4761112/?ref_=adv_li_tt",
            "desc": "Mohamedou Ould Slahi fights for freedom after being detained and imprisoned without charge by the U.S. Government for years.",
            "youtubeurl": "https://www.youtube.com/embed/7tmxxzZXLEM",
            "rating": "7.4",
            "genre": "Drama, Thriller",
            "year": "2021",
            "star": "Tahar Rahim, Nouhe Hamady Bari, Saadna Hamoud, Mohamed Yeslem Mousse",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/17.png?raw=true",
            "runtime": "129 min"
        },
        {
            "id": "18",
            "title": "Black Widow",
            "url": "https://www.imdb.com/title/tt3480822/?ref_=adv_li_tt",
            "desc": "A film about Natasha Romanoff in her quests between the films Civil War and Infinity War.",
            "youtubeurl": "https://www.youtube.com/embed/Fp9pNPdNwjI",
            "genre": "Action, Adventure, Sci-Fi",
            "year": "2021",
            "star": "Scarlett Johansson, Florence Pugh, David Harbour, Rachel Weisz",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/18.png?raw=true",
            "runtime": "133 min"
        },
        {
            "id": "19",
            "title": "Tom and Jerry",
            "url": "https://www.imdb.com/title/tt1361336/?ref_=adv_li_tt",
            "desc": "A chaotic battle ensues between Jerry Mouse, who has taken refuge in the Royal Gate Hotel, and Tom Cat, who is hired to drive him away before the day of a big wedding arrives.",
            "youtubeurl": "https://www.youtube.com/embed/kP9TfCWaQT4",
            "rating": "5.2",
            "genre": "Animation, Comedy, Family",
            "year": "2021",
            "star": "Chloë Grace Moretz, Michael Peña, Colin Jost, Tom",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/19.png?raw=true",
            "runtime": "101 min"
        },
        {
            "id": "20",
            "title": "The Little Things",
            "url": "https://www.imdb.com/title/tt10016180/?ref_=adv_li_tt",
            "desc": "Kern County Deputy Sheriff Joe Deacon is sent to Los Angeles for what should have been a quick evidence-gathering assignment. Instead, he becomes embroiled in the search for a serial killer who is terrorizing the city.",
            "youtubeurl": "https://www.youtube.com/embed/1HZAnkxdYuA",
            "rating": "6.3",
            "genre": "Crime, Drama, Thriller",
            "year": "2021",
            "star": "Denzel Washington, Rami Malek, Jared Leto, Chris Bauer",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/20.png?raw=true",
            "runtime": "128 min"
        },
        {
            "id": "21",
            "title": "Paper Lives",
            "url": "https://www.imdb.com/title/tt13045890/?ref_=adv_li_tt",
            "desc": "Mehmet is a cherished fellow who runs the solid waste warehouse in the neighborhood, he helps everyone in need, especially homeless children and teenagers since he was one too.",
            "youtubeurl": "https://www.youtube.com/embed/lXdSaVK-vzs",
            "rating": "6.5",
            "genre": "Drama",
            "year": "2021",
            "star": "Çagatay Ulusoy, Emir Ali Dogrul, Ersin Arici, Turgay Tanülkü",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/21.png?raw=true",
            "runtime": "96 min"
        },
        {
            "id": "22",
            "title": "Nobody (I)",
            "url": "https://www.imdb.com/title/tt7888964/?ref_=adv_li_tt",
            "desc": "A bystander who intervenes to help a woman being harassed by a group of men becomes the target of a vengeful drug lord.",
            "youtubeurl": "https://www.youtube.com/embed/wZti8QKBWPo",
            "rating": "7.8",
            "genre": "Action, Crime, Drama",
            "year": "2021",
            "star": "Bob Odenkirk, Aleksey Serebryakov, Connie Nielsen, Christopher Lloyd",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/22.png?raw=true",
            "runtime": "92 min"
        },
        {
            "id": "23",
            "title": "The Suicide Squad",
            "url": "https://www.imdb.com/title/tt6334354/?ref_=adv_li_tt",
            "desc": "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
            "youtubeurl": "https://www.youtube.com/embed/Z1EbSXxrZ34",
            "genre": "Action, Adventure, Fantasy",
            "year": "2021",
            "star": "Margot Robbie, Idris Elba, John Cena, Joel Kinnaman",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/23.png?raw=true"
        },
        {
            "id": "24",
            "title": "The Dig",
            "url": "https://www.imdb.com/title/tt3661210/?ref_=adv_li_tt",
            "desc": "An archaeologist embarks on the historically important excavation of Sutton Hoo in 1938.",
            "youtubeurl": "https://www.youtube.com/embed/JZQz0rkNajo",
            "rating": "7.1",
            "genre": "Biography, Drama, History",
            "year": "2021",
            "star": "Carey Mulligan, Ralph Fiennes, Lily James, Johnny Flynn",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/24.png?raw=true",
            "runtime": "112 min"
        },
        {
            "id": "25",
            "title": "Cosmic Sin",
            "url": "https://www.imdb.com/title/tt11762434/?ref_=adv_li_tt",
            "desc": "Seven rogue soldiers launch a preemptive strike against a newly discovered alien civilization in the hopes of ending an interstellar war before it starts.",
            "youtubeurl": "https://www.youtube.com/embed/MNxsB6o6DJs",
            "rating": "2.5",
            "genre": "Action, Adventure, Sci-Fi",
            "year": "2021",
            "star": "Frank Grillo, Bruce Willis, Brandon Thomas Lee, Corey Large",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/25.png?raw=true",
            "runtime": "88 min"
        },
        {
            "id": "26",
            "title": "Cruella",
            "url": "https://www.imdb.com/title/tt3228774/?ref_=adv_li_tt",
            "desc": "A live-action prequel feature film following a young Cruella de Vil.",
            "youtubeurl": "https://www.youtube.com/embed/gmRKv7n2If8",
            "genre": "Comedy, Crime",
            "year": "2021",
            "star": "Emma Stone, Mark Strong, Emma Thompson, Paul Walter Hauser",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/26.png?raw=true"
        },
        {
            "id": "27",
            "title": "Crisis",
            "url": "https://www.imdb.com/title/tt9731682/?ref_=adv_li_tt",
            "desc": "Three stories about the world of opioids collide: a drug trafficker arranges a multi-cartel Fentanyl smuggling operation between Canada and the U.S., an architect recovering from an oxycodone addiction tracks down the truth behind her son's involvement with narcotics, and a university professor battles unexpected revelations about his research employer, a drug company with deep government influence bringing a new \"non-addictive\" painkiller to market.",
            "youtubeurl": "https://www.youtube.com/embed/Y0JZVfQFqos",
            "rating": "6.1",
            "genre": "Drama, Thriller",
            "year": "2021",
            "star": "Gary Oldman, Armie Hammer, Evangeline Lilly, Greg Kinnear",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/27.png?raw=true",
            "runtime": "118 min"
        },
        {
            "id": "28",
            "title": "Army of the Dead",
            "url": "https://www.imdb.com/title/tt0993840/?ref_=adv_li_tt",
            "desc": "Following a zombie outbreak in Las Vegas, a group of mercenaries take the ultimate gamble, venturing into the quarantine zone to pull off the greatest heist ever attempted.",
            "youtubeurl": "https://www.youtube.com/embed/tI1JGPhYBS8",
            "genre": "Action, Crime, Horror",
            "year": "2021",
            "star": "Dave Bautista, Ella Purnell, Ana de la Reguera, Samantha Win",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/28.png?raw=true"
        },
        {
            "id": "29",
            "title": "Spider-Man: No Way Home",
            "url": "https://www.imdb.com/title/tt10872600/?ref_=adv_li_tt",
            "desc": "A continuation of Spider-Man Far From Home",
            "youtubeurl": "https://www.youtube.com/embed/r7M-XNGT5G0",
            "genre": "Action, Adventure, Sci-Fi",
            "year": "2021",
            "star": "Tom Holland, Benedict Cumberbatch, Zendaya, Marisa Tomei",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/29.png?raw=true"
        },
        {
            "id": "30",
            "title": "Voyagers",
            "url": "https://www.imdb.com/title/tt9664108/?ref_=adv_li_tt",
            "desc": "A crew of astronauts on a multi-generational mission descend into paranoia and madness, not knowing what is real or not.",
            "youtubeurl": "https://www.youtube.com/embed/EwJkexUBSeg",
            "genre": "Adventure, Sci-Fi, Thriller",
            "year": "2021",
            "star": "Colin Farrell, Tye Sheridan, Lily-Rose Depp, Isaac Hempstead Wright",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/30.png?raw=true",
            "runtime": "108 min"
        },
        {
            "id": "31",
            "title": "The United States vs. Billie Holiday\n",
            "url": "https://www.imdb.com/title/tt8521718/?ref_=adv_li_tt",
            "desc": "Follows Holiday during her career as she is targeted by the Federal Department of Narcotics with an undercover sting operation led by black Federal Agent Jimmy Fletcher, with whom she had a tumultuous affair.",
            "youtubeurl": "https://www.youtube.com/embed/USi-ppCfxEA",
            "rating": "6.3",
            "genre": "Biography, Drama, Music",
            "year": "2021",
            "star": "Andra Day, Trevante Rhodes, Garrett Hedlund, Natasha Lyonne",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/31.png?raw=true",
            "runtime": "130 min"
        },
        {
            "id": "32",
            "title": "Wrong Turn",
            "url": "https://www.imdb.com/title/tt9110170/?ref_=adv_li_tt",
            "desc": "Friends hiking the Appalachian Trail are confronted by 'The Foundation', a community of people who have lived in the mountains for hundreds of years.",
            "youtubeurl": "https://www.youtube.com/embed/ccaNMcPqpQ0",
            "rating": "5.4",
            "genre": "Horror, Thriller",
            "year": "2021",
            "star": "Charlotte Vega, Adain Bradley, Bill Sage, Emma Dumont",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/32.png?raw=true",
            "runtime": "109 min"
        },
        {
            "id": "33",
            "title": "Dune",
            "url": "https://www.imdb.com/title/tt1160419/?ref_=adv_li_tt",
            "desc": "Feature adaptation of Frank Herbert's science fiction novel, about the son of a noble family entrusted with the protection of the most valuable asset and most vital element in the galaxy.",
            "youtubeurl": "https://www.youtube.com/embed/n9xhJrPXop4",
            "genre": "Adventure, Drama, Sci-Fi",
            "year": "2021",
            "star": "Jason Momoa, Zendaya, Rebecca Ferguson, Timothée Chalamet",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/33.png?raw=true"
        },
        {
            "id": "34",
            "title": "Girl in the Basement",
            "url": "https://www.imdb.com/title/tt13269536/?ref_=adv_li_tt",
            "desc": "Sara is a teen girl who is looking forward to her 18th birthday to move away from her controlling father Don. But before she could even blow out the candles, Don imprisons her in the basement of their home.",
            "youtubeurl": "https://www.youtube.com/embed/YDdYA8Af4uI",
            "rating": "6.3",
            "genre": "Crime, Thriller",
            "year": "2021",
            "star": "Jake Etheridge, Sydney Kowalske, Liam Pileggi, Emma Myers",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/34.png?raw=true",
            "runtime": "88 min"
        },
        {
            "id": "35",
            "title": "Happily",
            "url": "https://www.imdb.com/title/tt9849004/?ref_=adv_li_tt",
            "desc": "A dark romantic comedy. Tom and Janet have been happily married for years. But a visit from a mysterious stranger leads to a dead body, a lot of questions, and a tense couples' trip with friends who may not actually be friends at all.",
            "youtubeurl": "https://www.youtube.com/embed/nagyNvw5Dmk",
            "rating": "5.2",
            "genre": "Comedy, Crime, Romance",
            "year": "2021",
            "star": "Kerry Bishé, Joel McHale, Al Madrigal, Natalie Zea",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/35.png?raw=true",
            "runtime": "96 min"
        },
        {
            "id": "36",
            "title": "The White Tiger",
            "url": "https://www.imdb.com/title/tt6571548/?ref_=adv_li_tt",
            "desc": "An ambitious Indian driver uses his wit and cunning to escape from poverty and rise to the top. An epic journey based on the New York Times bestseller.",
            "youtubeurl": "https://www.youtube.com/embed/35jJNyFuYKQ",
            "rating": "7.2",
            "genre": "Crime, Drama",
            "year": "2021",
            "star": "Adarsh Gourav, Rajkummar Rao, Priyanka Chopra, Vedant Sinha",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/36.png?raw=true",
            "runtime": "125 min"
        },
        {
            "id": "37",
            "title": "The Matrix 4",
            "url": "https://www.imdb.com/title/tt10838180/?ref_=adv_li_tt",
            "desc": "The plot is currently unknown.",
            "youtubeurl": "https://www.youtube.com/embed/PkhXLgu-mYM",
            "genre": "Action, Sci-Fi",
            "year": "2021",
            "star": "Keanu Reeves, Priyanka Chopra, Carrie-Anne Moss, Jessica Henwick",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/37.png?raw=true"
        },
        {
            "id": "38",
            "title": "No Time to Die",
            "url": "https://www.imdb.com/title/tt2382320/?ref_=adv_li_tt",
            "desc": "James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.",
            "youtubeurl": "https://www.youtube.com/embed/BIhNsAtPbPI",
            "genre": "Action, Adventure, Thriller",
            "year": "2021",
            "star": "Daniel Craig, Ana de Armas, Rami Malek, Ralph Fiennes",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/38.png?raw=true",
            "runtime": "163 min"
        },
        {
            "id": "39",
            "title": "Free Guy",
            "url": "https://www.imdb.com/title/tt6264654/?ref_=adv_li_tt",
            "desc": "A bank teller discovers that he's actually an NPC inside a brutal, open world video game.",
            "youtubeurl": "https://www.youtube.com/embed/JORN2hkXLyM",
            "rating": "7.5",
            "genre": "Action, Adventure, Comedy",
            "year": "2021",
            "star": "Ryan Reynolds, Jodie Comer, Taika Waititi, Joe Keery",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/39.png?raw=true"
        },
        {
            "id": "40",
            "title": "Eternals",
            "url": "https://www.imdb.com/title/tt9032400/?ref_=adv_li_tt",
            "desc": "The saga of the Eternals, a race of immortal beings who lived on Earth and shaped its history and civilizations.",
            "youtubeurl": "https://www.youtube.com/embed/kfYXdkjzrmk",
            "genre": "Action, Adventure, Drama",
            "year": "2021",
            "star": "Gemma Chan, Angelina Jolie, Salma Hayek, Richard Madden",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/40.png?raw=true"
        },
        {
            "id": "41",
            "title": "Sentinelle",
            "url": "https://www.imdb.com/title/tt11734264/?ref_=adv_li_tt",
            "desc": "Transferred home after a traumatizing combat mission, a trained French soldier uses her lethal skills to hunt down the man who hurt her sister.",
            "youtubeurl": "https://www.youtube.com/embed/wAJcykyq7DU",
            "rating": "4.7",
            "genre": "Action, Drama, Thriller",
            "year": "2021",
            "star": "Olga Kurylenko, Marilyn Lima, Michel Nabokoff, Martin Swabey",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/41.png?raw=true",
            "runtime": "80 min"
        },
        {
            "id": "42",
            "title": "Willy's Wonderland",
            "url": "https://www.imdb.com/title/tt8114980/?ref_=adv_li_tt",
            "desc": "A quiet drifter is tricked into a janitorial job at the now condemned Willy's Wonderland. The mundane tasks suddenly become an all-out fight for survival against wave after wave of demonic animatronics. Fists fly, kicks land, titans clash -- and only one side will make it out alive.",
            "youtubeurl": "https://www.youtube.com/embed/jO9lc3wzifY",
            "rating": "5.6",
            "genre": "Action, Comedy, Horror",
            "year": "2021",
            "star": "Nicolas Cage, Emily Tosta, Beth Grant, Ric Reitz",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/42.png?raw=true",
            "runtime": "88 min"
        },
        {
            "id": "43",
            "title": "Palmer",
            "url": "https://www.imdb.com/title/tt6857376/?ref_=adv_li_tt",
            "desc": "An ex-convict strikes up a friendship with a boy from a troubled home.",
            "youtubeurl": "https://www.youtube.com/embed/OABSI3eYOk0",
            "rating": "7.3",
            "genre": "Drama",
            "year": "2021",
            "star": "Justin Timberlake, Juno Temple, Alisha Wainwright, Ryder Allen",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/43.png?raw=true",
            "runtime": "110 min"
        },
        {
            "id": "44",
            "title": "Top Gun: Maverick",
            "url": "https://www.imdb.com/title/tt1745960/?ref_=adv_li_tt",
            "desc": "After more than thirty years of service as one of the Navy's top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.",
            "youtubeurl": "https://www.youtube.com/embed/qSqVVswa420",
            "genre": "Action, Drama",
            "year": "2021",
            "star": "Tom Cruise, Jennifer Connelly, Miles Teller, Danny Ramirez",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/44.png?raw=true"
        },
        {
            "id": "45",
            "title": "Mission: Impossible 7",
            "url": "https://www.imdb.com/title/tt9603212/?ref_=adv_li_tt",
            "desc": "Seventh entry in the long-running Mission: Impossible series.",
            "youtubeurl": "https://www.youtube.com/embed/l-zfdarsQH0",
            "genre": "Action, Adventure, Thriller",
            "year": "2021",
            "star": "Vanessa Kirby, Tom Cruise, Rebecca Ferguson, Hayley Atwell",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/45.png?raw=true"
        },
        {
            "id": "46",
            "title": "Venom: Let There Be Carnage",
            "url": "https://www.imdb.com/title/tt7097896/?ref_=adv_li_tt",
            "desc": "Plot unknown. Sequel to the 2018 film 'Venom'.",
            "youtubeurl": "https://www.youtube.com/embed/PR2MOy5W1oY",
            "genre": "Action, Horror, Sci-Fi",
            "year": "2021",
            "star": "Tom Hardy, Michelle Williams, Woody Harrelson, Stephen Graham",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/46.png?raw=true"
        },
        {
            "id": "47",
            "title": "Jathi Ratnalu",
            "url": "https://www.imdb.com/title/tt11306376/?ref_=adv_li_tt",
            "desc": "The plot revolves around the three prisoners. They get released and plan for a happy life outside. Things take a new turn and bring in a twist. Can they find happiness and love now?",
            "youtubeurl": "https://www.youtube.com/embed/Hgc07_BX4_8",
            "rating": "8.3",
            "genre": "Comedy",
            "year": "2021",
            "star": "Naveen Polishetty, Priyadarshi, Rahul Ramakrishna, Faria Abdullah",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/47.png?raw=true",
            "runtime": "145 min"
        },
        {
            "id": "48",
            "title": "Trust (II)",
            "url": "https://www.imdb.com/title/tt3986420/?ref_=adv_li_tt",
            "desc": "In this sexy and twisty ride, New York gallery owner Brooke and her husband Owen each face exceptional temptations, with most unexpected results.",
            "youtubeurl": "https://www.youtube.com/embed/tnr9frEhy7E",
            "rating": "5.6",
            "genre": "Drama, Romance",
            "year": "2021",
            "star": "Victoria Justice, Matthew Daddario, Katherine McNamara, Lucien Laviscount",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/48.png?raw=true",
            "runtime": "94 min"
        },
        {
            "id": "49",
            "title": "F9",
            "url": "https://www.imdb.com/title/tt5433138/?ref_=adv_li_tt",
            "desc": "Cypher enlists the help of Jakob, Dom's younger brother to take revenge on Dom and his team.",
            "youtubeurl": "https://www.youtube.com/embed/aSiDu3Ywi8E",
            "genre": "Action, Adventure, Crime",
            "year": "2021",
            "star": "Vin Diesel, Michelle Rodriguez, Charlize Theron, Michael Rooker",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/49.png?raw=true",
            "runtime": "145 min"
        },
        {
            "id": "50",
            "title": "House of Gucci",
            "url": "https://www.imdb.com/title/tt11214590/?ref_=adv_li_tt",
            "desc": "The story of how Patrizia Reggiani, the ex-wife of Maurizio Gucci, plotted to kill her husband, the grandson of renowned fashion designer Guccio Gucci.",
            "youtubeurl": "https://www.youtube.com/embed/rj4yXxYhH_0",
            "genre": "Crime, Drama, Thriller",
            "year": "2021",
            "star": "Jared Leto, Al Pacino, Adam Driver, Jeremy Irons",
            "imgurl": "https://raw.githubusercontent.com/aditya-dk7/movieAPI/main/resized_image_api/50.png?raw=true"
        }
    ]
